FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --omit=dev

# Copy application files
COPY obervability ./obervability
COPY server.js ./

# Expose application port
EXPOSE 3000

# Start the application
CMD ["node", "server.js"]
